/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarSucursalRequest { 
    SUC_nombre: string;
    SUC_ciudad: string;
    SUC_direccion: string;
    SUC_coordenadas?: string | null;
}

