/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarCategoriaVehiculoRequest { 
    CAT_nombre?: string | null;
    CAT_descripcion?: string | null;
    CAT_costoBase?: number;
}

