/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarClienteRequest { 
    CLI_id?: string;
    CLI_nombres?: string | null;
    CLI_apellidos?: string | null;
    CLI_cedula?: string | null;
    CLI_telefono?: string | null;
    CLI_usuarioModificacion?: string | null;
}

