/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarTarifaRequest { 
    TAR_id?: string;
    CAT_id?: string;
    TAR_precioDiario?: number;
    TAR_usuarioModificacion?: string | null;
}

