/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoriaVehiculoResponse } from './categoriaVehiculoResponse';


export interface CategoriaVehiculoResponseIReadOnlyListApiResponse { 
    Success?: boolean;
    Message?: string | null;
    Data?: Array<CategoriaVehiculoResponse> | null;
    Errors?: Array<string> | null;
}

