/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearClienteRequest { 
    CLI_nombres: string;
    CLI_apellidos: string;
    CLI_cedula: string;
    CLI_telefono?: string | null;
    CLI_usuarioCreacion?: string | null;
}

