/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearReservaRequest { 
    CLI_id?: string;
    RES_sucursalRetiroId?: string;
    RES_sucursalEntregaId?: string;
    RES_fechaRetiro?: string;
    RES_fechaEntrega?: string;
    RES_estado?: string | null;
    RES_usuarioCreacion?: string | null;
}

