/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearVehiculoRequest { 
    CAT_id?: string;
    SUC_id?: string;
    VEH_placa?: string | null;
    VEH_modelo?: string | null;
    VEH_anio?: number;
    VEH_color?: string | null;
    VEH_kilometraje?: number;
    VEH_estado?: string | null;
    VEH_usuarioCreacion?: string | null;
}

