/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearUsuarioAppRequest { 
    ROL_id?: string;
    USU_email?: string | null;
    USU_passwordHash?: string | null;
    USU_usuarioCreacion?: string | null;
}

