/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtraAdicionalResponse } from './extraAdicionalResponse';


export interface ExtraAdicionalResponseApiResponse { 
    Success?: boolean;
    Message?: string | null;
    Data?: ExtraAdicionalResponse;
    Errors?: Array<string> | null;
}

