/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagoResponse } from './pagoResponse';


export interface PagoResponseDataPagedResult { 
    Items?: Array<PagoResponse> | null;
    PageNumber?: number;
    PageSize?: number;
    TotalRecords?: number;
}

