/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagoResponse } from './pagoResponse';


export interface PagoResponseIReadOnlyListApiResponse { 
    Success?: boolean;
    Message?: string | null;
    Data?: Array<PagoResponse> | null;
    Errors?: Array<string> | null;
}

