/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RolResponse { 
    ROL_id?: string;
    ROL_nombre?: string | null;
    ROL_fechaCreacion?: string | null;
    ROL_usuarioCreacion?: string | null;
    ROL_fechaModificacion?: string | null;
    ROL_usuarioModificacion?: string | null;
}

