/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SeguroResponse { 
    SEG_id?: string;
    SEG_nombre?: string | null;
    SEG_costoDiario?: number;
}

