/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SucursalResponse } from './sucursalResponse';


export interface SucursalResponseIReadOnlyListApiResponse { 
    Success?: boolean;
    Message?: string | null;
    Data?: Array<SucursalResponse> | null;
    Errors?: Array<string> | null;
}

