/**
 * Microservicio.Coche.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SucursalResponse { 
    SUC_id?: string;
    SUC_nombre?: string | null;
    SUC_ciudad?: string | null;
    SUC_direccion?: string | null;
    SUC_coordenadas?: string | null;
    SUC_fechaCreacion?: string | null;
    SUC_usuarioCreacion?: string | null;
    SUC_fechaModificacion?: string | null;
    SUC_usuarioModificacion?: string | null;
}

