export * from './auth.service';
import { AuthService } from './auth.service';
export * from './categoriasVehiculo.service';
import { CategoriasVehiculoService } from './categoriasVehiculo.service';
export * from './clientes.service';
import { ClientesService } from './clientes.service';
export * from './extraAdicionales.service';
import { ExtraAdicionalesService } from './extraAdicionales.service';
export * from './reservas.service';
import { ReservasService } from './reservas.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './seguros.service';
import { SegurosService } from './seguros.service';
export * from './sucursales.service';
import { SucursalesService } from './sucursales.service';
export * from './tarifas.service';
import { TarifasService } from './tarifas.service';
export * from './usuariosApp.service';
import { UsuariosAppService } from './usuariosApp.service';
export * from './vehiculos.service';
import { VehiculosService } from './vehiculos.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AuthService, CategoriasVehiculoService, ClientesService, ExtraAdicionalesService, ReservasService, RolesService, SegurosService, SucursalesService, TarifasService, UsuariosAppService, VehiculosService, WeatherForecastService];
